STUDENT NAME : AMOGH DATH KALASAPURA ARUNKUMAR


STUDENT ID : 24168333



STUDENT EMAIL : amoghdath.kalasapuraarunkumar@mail.bcu.ac.uk


LAB COMPLETION DATE : 4TH OCT 2025

**Start by doing the following**



1.   Go to your [lab2](https://moodle.bcu.ac.uk/mod/folder/view.php?id=8931483) on your Moodle. Download the dataset 'rollingsales_bronx.xls' from moodle and upload it in your colab
2.   Download the Lab Example notebook and upload in your Google Drive and open it beside this one.
3.   Check each relevant section in the example noteobook to be able to answer the questions below

# **Exercise 1 for Lab 2**

In [35]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_excel("/content/rollingsales_bronx.xlsx") # Loads the dataset.

# Preview data
df.head() # Provides the first 5 values of the dataset.

#There is an issue with this dataset. The issues are :-
#  A. The dataset contains unnamed columns.
#  B. The dataset contains missing values in the first three rows.

,Bronx Rolling Sales. All Sales From September 2023 - August 2024,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,PTS Sales Data as of 09/06/2024,Unnamed: 20
0,"For sales prior to the Final Roll, Neighborhoo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Building Class Category is based on Building C...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Note: Condominium and cooperative sales are on...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASEMENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
4,2,BATHGATE,NaN,1,2907,24,NaN,A1,4090 PARK AVENUE,NaN,...,1,0,1,2500,1474,1901,1,A1,0,2024-03-28 00:00:00

In [36]:
#The solutions for the issues is to read the data in again but skip 4 rows this time, then take row [0] after cleaning as header
df = pd.read_excel("/content/rollingsales_bronx.xlsx", skiprows = 4, header = [0])

# preview data - After sorting the 2 issues
df.head() # provides the first 5 values of the dataset

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASEMENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,2,BATHGATE,NaN,1,2907,24,NaN,A1,4090 PARK AVENUE,NaN,...,1.0,0.0,1.0,2500.0,1474.0,1901.0,1,A1,0,2024-03-28
1,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3046,27,NaN,A1,2090 WASHINGTON AVENUE,NaN,...,1.0,0.0,1.0,2356.0,2213.0,NaN,1,A1,0,2024-06-11
2,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3046,40,NaN,A1,2073 BATHGATE AVENUE,NaN,...,1.0,0.0,1.0,1933.0,1344.0,NaN,1,A1,425000,2024-06-27
3,2,BATHGATE,NaN,1,3047,11,NaN,A1,482 EAST 181ST STREET,NaN,...,1.0,0.0,1.0,1556.0,1240.0,1901.0,1,A1,0,2024-06-14
4,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3050,91,NaN,A9,503 EAST 182 STREET,NaN,...,1.0,0.0,1.0,1960.0,1705.0,NaN,1,A9,515000,2024-04-11

## **1. Clean the dataset header and rename columns as in the lab example (Hint check Section 1. Data Cleaning in Lab2 Example).**

In [37]:
#Extract columns
cols = df.columns
#Create empty list
new_cols = []
#iterate to fix issues with names
for column in cols:
  proper_cols = column.title() # turns into proper case
  # replace space/hyphen with underscore
  proper_cols_hyphen = proper_cols.replace(" ", "_")
  clean_cols = proper_cols_hyphen.replace("-", "_")
  new_cols.append(clean_cols) # append to empty list

# #replace existing columns in dataframe with new
df.columns = new_cols

#preview the changes
df.head()

,Borough,Neighborhood,Building_Class_Category,Tax_Class_At_Present,Block,Lot,Easement,Building_Class_At_Present,Address,Apartment_Number,...,Residential_Units,Commercial_Units,Total_Units,Land_Square_Feet,Gross_Square_Feet,Year_Built,Tax_Class_At_Time_Of_Sale,Building_Class_At_Time_Of_Sale,Sale_Price,Sale_Date
0,2,BATHGATE,NaN,1,2907,24,NaN,A1,4090 PARK AVENUE,NaN,...,1.0,0.0,1.0,2500.0,1474.0,1901.0,1,A1,0,2024-03-28
1,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3046,27,NaN,A1,2090 WASHINGTON AVENUE,NaN,...,1.0,0.0,1.0,2356.0,2213.0,NaN,1,A1,0,2024-06-11
2,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3046,40,NaN,A1,2073 BATHGATE AVENUE,NaN,...,1.0,0.0,1.0,1933.0,1344.0,NaN,1,A1,425000,2024-06-27
3,2,BATHGATE,NaN,1,3047,11,NaN,A1,482 EAST 181ST STREET,NaN,...,1.0,0.0,1.0,1556.0,1240.0,1901.0,1,A1,0,2024-06-14
4,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3050,91,NaN,A9,503 EAST 182 STREET,NaN,...,1.0,0.0,1.0,1960.0,1705.0,NaN,1,A9,515000,2024-04-11

In [38]:
# Checking the data-types to understand the dataset configuration
df.dtypes #Resolves as an object type.

Borough                                    int64
Neighborhood                              object
Building_Class_Category                   object
Tax_Class_At_Present                      object
Block                                      int64
Lot                                        int64
Easement                                 float64
Building_Class_At_Present                 object
Address                                   object
Apartment_Number                          object
Zip_Code                                   int64
Residential_Units                        float64
Commercial_Units                         float64
Total_Units                              float64
Land_Square_Feet                         float64
Gross_Square_Feet                        float64
Year_Built                               float64
Tax_Class_At_Time_Of_Sale                  int64
Building_Class_At_Time_Of_Sale            object
Sale_Price                                 int64
Sale_Date                         datetime64[ns]
dtype: object

## **2. Check missing data (Hint check  Section 2 Missing Data  in the Lab2 Example):**
  **A. check missing data in the whole dataset**

  **B. Fill in the missing data in **Total_Units** column with the appropriate value based on your analysis**

In [39]:
#Check missing data by checking how many nulls
print("Missing data in the dataset:")
df.isnull().sum()  # This provides the missing values in the dataset

Missing data in the dataset:

Borough                              0
Neighborhood                         0
Building_Class_Category              2
Tax_Class_At_Present                 0
Block                                0
Lot                                  0
Easement                          5718
Building_Class_At_Present            0
Address                              0
Apartment_Number                  5197
Zip_Code                             0
Residential_Units                 1127
Commercial_Units                  1603
Total_Units                       1100
Land_Square_Feet                  1630
Gross_Square_Feet                 1630
Year_Built                         619
Tax_Class_At_Time_Of_Sale            0
Building_Class_At_Time_Of_Sale       0
Sale_Price                           0
Sale_Date                            0
dtype: int64

In [40]:
# Also check the percentage of missing data
missing_pct = round(df.isnull().sum()/len(df) * 100, 1)
print("\nMissing data percentage:")
print(missing_pct)

Missing data percentage:
Borough                             0.0
Neighborhood                        0.0
Building_Class_Category             0.0
Tax_Class_At_Present                0.0
Block                               0.0
Lot                                 0.0
Easement                          100.0
Building_Class_At_Present           0.0
Address                             0.0
Apartment_Number                   90.9
Zip_Code                            0.0
Residential_Units                  19.7
Commercial_Units                   28.0
Total_Units                        19.2
Land_Square_Feet                   28.5
Gross_Square_Feet                  28.5
Year_Built                         10.8
Tax_Class_At_Time_Of_Sale           0.0
Building_Class_At_Time_Of_Sale      0.0
Sale_Price                          0.0
Sale_Date                           0.0
dtype: float64

In [41]:
#Check how many nulls in the Total_Units column
print("Total Number of null values in Total_Units column:", df['Total_Units'].isnull().sum())
print("Percentage of null values in Total_Units column:", round(df['Total_Units'].isnull().sum()/len(df) * 100, 1), "%")

Total Number of null values in Total_Units column: 1100
Percentage of null values in Total_Units column: 19.2 %

In [42]:
#Check skewdness for this column
print("Skewness of Total_Units column:", df['Total_Units'].skew())
print("Mean:", df['Total_Units'].mean())
print("Median:", df['Total_Units'].median())
print("Mode:", df['Total_Units'].mode()[0] if not df['Total_Units'].mode().empty else "No mode")

Skewness of Total_Units column: 12.648391266422264
Mean: 3.631875270679948
Median: 2.0
Mode: 1.0

**Give your interpretation of the results**

1.   List item

---------------------> Solution-01 <--------------------
1. **Skewness Interpretation**: If the skewness value is > 1 or < -1, the data is highly skewed. If skewness ≈ 0, the data is roughly normally distributed.





2.   List item

---------------------> Solution-02 <--------------------

2. **Filling Strategy**:
   - **Highly skewed data** (|skewness| > 1): Use **median** for filling missing values because median is robust to outliers and better represents the central tendency
   - **Normal data** (skewness ≈ 0): Use **mean** for filling missing values as it provides the best central measure
   - **Rule of thumb**: When mean and median are very different, the data is likely skewed and median should be preferred

In [43]:
# You can now fill the Total_Units with your chosen method.
# Based on skewness analysis, if highly skewed use median, if normal use mean

# Check skewness first to decide the method
skewness = df['Total_Units'].skew()
print(f"Skewness: {skewness}")

if abs(skewness) > 1:
    # Highly skewed - use median
    fill_value = df['Total_Units'].median()
    print(f"Using median: {fill_value}")
else:
    # Roughly normal - use mean
    fill_value = df['Total_Units'].mean()
    print(f"Using mean: {fill_value}")

# Fill missing values
df['Total_Units'] = df['Total_Units'].fillna(fill_value)

Skewness: 12.648391266422264
Using median: 2.0

In [44]:
# Now check if there are missing values for Total_Units
print("Missing values in Total_Units after filling:", df['Total_Units'].isnull().sum())
print("Verification: All missing values filled successfully!")

Missing values in Total_Units after filling: 0
Verification: All missing values filled successfully!

## **3. Check the mean, mode, median and standard deviation of the Sale_Price column**

In [45]:
# print each one in a seperate line
print("Sale_Price Statistics:")
print("Mean:", df['Sale_Price'].mean())
print("Median:", df['Sale_Price'].median())
print("Mode:", df['Sale_Price'].mode()[0] if not df['Sale_Price'].mode().empty else "No mode")
print("Standard Deviation:", df['Sale_Price'].std())

Sale_Price Statistics:
Mean: 673315.9783140959
Median: 295000.0
Mode: 0
Standard Deviation: 1515792.5640463387

## **4. Standarise the Gross_Square_Feet colum with the StandardScaler(). Fill in missing values first then standardise (Hint check Section 3: Data Scaling  in the lab example)**

In [46]:
#First check if it has missing values
print("Missing values in Gross_Square_Feet:", df['Gross_Square_Feet'].isnull().sum())
print("Percentage of missing values:", round(df['Gross_Square_Feet'].isnull().sum()/len(df) * 100, 1), "%")

Missing values in Gross_Square_Feet: 1630
Percentage of missing values: 28.5 %

In [47]:
#Fill the missing vallues with the a chosen method as in exercise 2 above
# Check skewness to decide the appropriate filling method
skewness_gross = df['Gross_Square_Feet'].skew()
print(f"Gross_Square_Feet skewness: {skewness_gross}")

if abs(skewness_gross) > 1:
    # Highly skewed - use median
    fill_value_gross = df['Gross_Square_Feet'].median()
    print(f"Using median: {fill_value_gross}")
else:
    # Roughly normal - use mean
    fill_value_gross = df['Gross_Square_Feet'].mean()
    print(f"Using mean: {fill_value_gross}")

Gross_Square_Feet skewness: 19.71750198218531
Using median: 2177.0

In [48]:
# You can now fill the missing value with your chosen method
df['Gross_Square_Feet'] = df['Gross_Square_Feet'].fillna(fill_value_gross)

In [49]:
# check if you cleaned all missing values from Gross_Square_Feet
print("Missing values in Gross_Square_Feet after filling:", df['Gross_Square_Feet'].isnull().sum())
print("Verification: All missing values filled successfully!")

Missing values in Gross_Square_Feet after filling: 0
Verification: All missing values filled successfully!

In [50]:
# Extract min and max for Gross_Square_Feet
Gross_Square_Feet_min = df['Gross_Square_Feet'].min()
Gross_Square_Feet_max = df['Gross_Square_Feet'].max()

# Display the comparison
print(f"Gross Square Feet Range: {Gross_Square_Feet_min :,.2f} to {Gross_Square_Feet_max :,.2f} sq ft")

Gross Square Feet Range: 0.00 to 1,172,005.00 sq ft

**Write your interpretation of the range**

The range analysis of Gross_Square_Feet reveals important insights about the dataset:

- **Data Scale**: The wide range indicates significant variation in building sizes in the Bronx real estate market
- **Outliers**: A large range suggests potential outliers or extreme values that may need attention during analysis
- **Standardization Need**: Such a wide range justifies the use of StandardScaler to normalize the data, as features with vastly different scales can bias machine learning models
- **Real Estate Context**: The range likely reflects the diversity of property types in the Bronx, from small residential units to large commercial buildings.

In [51]:
import pandas
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

from sklearn.preprocessing import StandardScaler
import pandas as pd
# Select and scale
X = df[['Gross_Square_Feet']]
# define your scaler
scaler = StandardScaler()
# Scale the data
scaledX = scaler.fit_transform(X)



#Now let's see the values after scaling (the mean should be 0 and standard deviation 1)
# Convert back to DataFrame
scaled_df = pd.DataFrame(scaledX, columns=['Gross_Square_Feet'])



# Print mean and std of scaled columns
print("Mean values:\n", scaled_df.mean())
print("\nStandard deviation values:\n", scaled_df.std())

Mean values:
 Gross_Square_Feet   -9.941137e-18
dtype: float64

Standard deviation values:
 Gross_Square_Feet    1.000087
dtype: float64

## **5. Impute the Building_Class_Category with a Lable Encoder (Hint check Section 4 Imputing Categorical Data in Lab example)**

In [52]:
# Check the values of the Building_Class_Category
print("Unique values in Building_Class_Category:")
print(df['Building_Class_Category'].unique())
print("\nValue counts:")
print(df['Building_Class_Category'].value_counts())

Unique values in Building_Class_Category:
[nan '01 ONE FAMILY DWELLINGS' '02 TWO FAMILY DWELLINGS'
 '03 THREE FAMILY DWELLINGS' '05 TAX CLASS 1 VACANT LAND'
 '07 RENTALS - WALKUP APARTMENTS' '10 COOPS - ELEVATOR APARTMENTS'
 '14 RENTALS - 4-10 UNIT' '21 OFFICE BUILDINGS' '22 STORE BUILDINGS'
 '29 COMMERCIAL GARAGES' '30 WAREHOUSES' '31 COMMERCIAL VACANT LAND'
 '37 RELIGIOUS FACILITIES' '41 TAX CLASS 4 - OTHER'
 '06 TAX CLASS 1 - OTHER' '26 OTHER HOTELS' '33 EDUCATIONAL FACILITIES'
 '08 RENTALS - ELEVATOR APARTMENTS' '09 COOPS - WALKUP APARTMENTS'
 '12 CONDOS - WALKUP APARTMENTS' '32 HOSPITAL AND HEALTH FACILITIES'
 '13 CONDOS - ELEVATOR APARTMENTS' '04 TAX CLASS 1 CONDOS'
 '17 CONDO COOPS' '27 FACTORIES' '38 ASYLUMS AND HOMES'
 '35 INDOOR PUBLIC AND CULTURAL FACILITIES' '44 CONDO PARKING'
 '47 CONDO NON-BUSINESS STORAGE' '43 CONDO OFFICE BUILDINGS'
 '11 SPECIAL CONDO BILLING LOTS' '28 COMMERCIAL CONDOS'
 '42 CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC' '46 CONDO STORE BUILDINGS'
 '15 CONDOS - 2-10 UNIT RESIDENTIAL']

Value counts:
Building_Class_Category
02 TWO FAMILY DWELLINGS                      1485
01 ONE FAMILY DWELLINGS                      1129
10 COOPS - ELEVATOR APARTMENTS                994
03 THREE FAMILY DWELLINGS                     627
13 CONDOS - ELEVATOR APARTMENTS               339
07 RENTALS - WALKUP APARTMENTS                250
05 TAX CLASS 1 VACANT LAND                    164
04 TAX CLASS 1 CONDOS                         134
29 COMMERCIAL GARAGES                          98
22 STORE BUILDINGS                             93
08 RENTALS - ELEVATOR APARTMENTS               73
09 COOPS - WALKUP APARTMENTS                   68
06 TAX CLASS 1 - OTHER                         36
31 COMMERCIAL VACANT LAND                      34
14 RENTALS - 4-10 UNIT                         31
30 WAREHOUSES                                  31
12 CONDOS - WALKUP APARTMENTS                  28
21 OFFICE BUILDINGS                            17
41 TAX CLASS 4 - OTHER                         15
44 CONDO PARKING                               14
37 RELIGIOUS FACILITIES                        11
27 FACTORIES                                    8
32 HOSPITAL AND HEALTH FACILITIES               5
46 CONDO STORE BUILDINGS                        5
17 CONDO COOPS                                  5
26 OTHER HOTELS                                 4
43 CONDO OFFICE BUILDINGS                       3
33 EDUCATIONAL FACILITIES                       2
38 ASYLUMS AND HOMES                            2
35 INDOOR PUBLIC AND CULTURAL FACILITIES        2
47 CONDO NON-BUSINESS STORAGE                   2
11 SPECIAL CONDO BILLING LOTS                   2
28 COMMERCIAL CONDOS                            2
15 CONDOS - 2-10 UNIT RESIDENTIAL               2
42 CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC       1
Name: count, dtype: int64

In [53]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Initialize encoder
le = LabelEncoder()

# Fit and transform
df['Building_Class_Category_encoded'] = le.fit_transform(df['Building_Class_Category'])

# View mapping
label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))

print("Label Mapping:\n", label_mapping)

Label Mapping:
 {'01 ONE FAMILY DWELLINGS': np.int64(0), '02 TWO FAMILY DWELLINGS': np.int64(1), '03 THREE FAMILY DWELLINGS': np.int64(2), '04 TAX CLASS 1 CONDOS': np.int64(3), '05 TAX CLASS 1 VACANT LAND': np.int64(4), '06 TAX CLASS 1 - OTHER': np.int64(5), '07 RENTALS - WALKUP APARTMENTS': np.int64(6), '08 RENTALS - ELEVATOR APARTMENTS': np.int64(7), '09 COOPS - WALKUP APARTMENTS': np.int64(8), '10 COOPS - ELEVATOR APARTMENTS': np.int64(9), '11 SPECIAL CONDO BILLING LOTS': np.int64(10), '12 CONDOS - WALKUP APARTMENTS': np.int64(11), '13 CONDOS - ELEVATOR APARTMENTS': np.int64(12), '14 RENTALS - 4-10 UNIT': np.int64(13), '15 CONDOS - 2-10 UNIT RESIDENTIAL': np.int64(14), '17 CONDO COOPS': np.int64(15), '21 OFFICE BUILDINGS': np.int64(16), '22 STORE BUILDINGS': np.int64(17), '26 OTHER HOTELS': np.int64(18), '27 FACTORIES': np.int64(19), '28 COMMERCIAL CONDOS': np.int64(20), '29 COMMERCIAL GARAGES': np.int64(21), '30 WAREHOUSES': np.int64(22), '31 COMMERCIAL VACANT LAND': np.int64(23), '32 HOSPITAL AND HEALTH FACILITIES': np.int64(24), '33 EDUCATIONAL FACILITIES': np.int64(25), '35 INDOOR PUBLIC AND CULTURAL FACILITIES': np.int64(26), '37 RELIGIOUS FACILITIES': np.int64(27), '38 ASYLUMS AND HOMES': np.int64(28), '41 TAX CLASS 4 - OTHER': np.int64(29), '42 CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC': np.int64(30), '43 CONDO OFFICE BUILDINGS': np.int64(31), '44 CONDO PARKING': np.int64(32), '46 CONDO STORE BUILDINGS': np.int64(33), '47 CONDO NON-BUSINESS STORAGE': np.int64(34), nan: np.int64(35)}