# WEEK ASSIGNMENT - LAB - O1
STUDENT NAME :- AMOGH DATH KALASAPURA ARUNKUMAR

STUDENT ID :- 24168333

In [36]:
# IMPORTING RELEVENT PYTHON LIBRARIES

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
# LOADING THE DATASET

df = pd.read_csv('/content/contact-lenses.csv')

In [37]:
# PROVIDES FIRST 6 RECORDS OF THE DATASET

(df.head(6))

     age spectacle_prescrip astigmatism tear_prod_rate contact_lenses
0  young              myope          no        reduced           none
1  young              myope          no         normal           soft
2  young              myope         yes        reduced           none
3  young              myope         yes         normal           hard
4  young       hypermetrope          no        reduced           none
5  young       hypermetrope          no         normal           soft

In [39]:
# PROVIDES LAST 3 RECORDS OF THE DATASET

(df.tail(3))

           age spectacle_prescrip astigmatism tear_prod_rate contact_lenses
21  presbyopic       hypermetrope          no         normal           soft
22  presbyopic       hypermetrope         yes        reduced           none
23  presbyopic       hypermetrope         yes         normal           none

In [31]:
# PROVIDES THE NAMES OF COLUMNS OF THE DATASET

display(df.columns)

Index(['Type', 'PW', 'PL', 'SW', 'SL', 'Species'], dtype='object')

In [40]:
# PROVIDES THE TYPES OF COLUMN VALUES OF THE DATA FRAME

display(df.dtypes)

age                   object
spectacle_prescrip    object
astigmatism           object
tear_prod_rate        object
contact_lenses        object
dtype: object

In [41]:
# PROVIDES THE LIST OF AGE GROUPS AND THE NUMBER OF INSTANCES IN EACH AGE GROUP

(df['age'].value_counts())

age
young             8
pre-presbyopic    8
presbyopic        8
Name: count, dtype: int64

In [42]:
# PROVIDES THE STATISTICAL INFORMATION OF THE DATASET

df.describe()

          age spectacle_prescrip astigmatism tear_prod_rate contact_lenses
count      24                 24          24             24             24
unique      3                  2           2              2              3
top     young              myope          no        reduced           none
freq        8                 12          12             12             15

In [43]:
# PROVIDES THE INFORMATION ABOUT THE THIRD RECORD OF THE DATASET

df.loc[2]

age                     young
spectacle_prescrip      myope
astigmatism               yes
tear_prod_rate        reduced
contact_lenses           none
Name: 2, dtype: object

In [44]:
# PROVIDES THE VALUE AT THE SECOND COLUMN OF THE FOURTH RECORD FROM THE DATA FRAME

df.iloc[3,1]

'myope'

In [11]:
# PROVIDES ALL THE RECORDS OF THE DATA FRAME WHERE THE CUSTOMER / PATIENT DOES NOT HAVE ASTIGMATISM

df[df['astigmatism'].str.contains('no')]

,age,spectacle_prescrip,astigmatism,tear_prod_rate,contact_lenses
0,young,myope,no,reduced,none
1,young,myope,no,normal,soft
4,young,hypermetrope,no,reduced,none
5,young,hypermetrope,no,normal,soft
8,pre-presbyopic,myope,no,reduced,none
9,pre-presbyopic,myope,no,normal,soft
12,pre-presbyopic,hypermetrope,no,reduced,none
13,pre-presbyopic,hypermetrope,no,normal,soft
16,presbyopic,myope,no,reduced,none
17,presbyopic,myope,no,normal,none
20,presbyopic,hypermetrope,no,reduced,none
21,presbyopic,hypermetrope,no,normal,soft

In [12]:
# PROVIDES ALL THE RECORDS OF THE DATA FRAME WHERE THE CUSTOMER / PATIENT IS YOUNG AND HAS SOFT CONTACT LENSES

df[(df['age'].str.contains('young')) & (df['contact_lenses'].str.contains('soft'))]

     age spectacle_prescrip astigmatism tear_prod_rate contact_lenses
1  young              myope          no         normal           soft
5  young       hypermetrope          no         normal           soft

In [13]:
# PROVIDES THE NUMBER OF ROWS AND COLUMNS OF THE DATASET

display(df.shape)

(24, 5)

In [46]:
# THIS SORTS THE DATA FRAME IN THE DECENDING ORDER BASED ON THE VALUES IN THE ASTIGMATISM COLUMNS

df.sort_values(by='astigmatism', ascending=False)

,age,spectacle_prescrip,astigmatism,tear_prod_rate,contact_lenses
23,presbyopic,hypermetrope,yes,normal,none
2,young,myope,yes,reduced,none
3,young,myope,yes,normal,hard
22,presbyopic,hypermetrope,yes,reduced,none
6,young,hypermetrope,yes,reduced,none
7,young,hypermetrope,yes,normal,hard
19,presbyopic,myope,yes,normal,hard
10,pre-presbyopic,myope,yes,reduced,none
11,pre-presbyopic,myope,yes,normal,hard
18,presbyopic,myope,yes,reduced,none
14,pre-presbyopic,hypermetrope,yes,reduced,none
15,pre-presbyopic,hypermetrope,yes,normal,none
16,presbyopic,myope,no,reduced,none
21,presbyopic,hypermetrope,no,normal,soft
20,presbyopic,hypermetrope,no,reduced,none
17,presbyopic,myope,no,normal,none
0,young,myope,no,reduced,none
13,pre-presbyopic,hypermetrope,no,normal,soft
1,young,myope,no,normal,soft
9,pre-presbyopic,myope,no,normal,soft
8,pre-presbyopic,myope,no,reduced,none
5,young,hypermetrope,no,normal,soft
4,young,hypermetrope,no,reduced,none
12,pre-presbyopic,hypermetrope,no,reduced,none

In [47]:
# SELECTS THE RECORD 2 TO 4 IN CONTACT LENSES DATA FRAME

df.iloc[2:5]

     age spectacle_prescrip astigmatism tear_prod_rate contact_lenses
2  young              myope         yes        reduced           none
3  young              myope         yes         normal           hard
4  young       hypermetrope          no        reduced           none

In [48]:
# SELECTS THOSE RECORDS THAT DO NOT HAVE ASTIGMATISM FROM RECORDS 2 TO 4 IN CONTACT LENSES DATA FRAME

df = df.iloc[2:5]
df[df['astigmatism'].str.contains('no')]

     age spectacle_prescrip astigmatism tear_prod_rate contact_lenses
4  young       hypermetrope          no        reduced           none

# EXERCISE - 05 ( IRIS DATASET )

In [67]:
# LOADING THE IRIS DATASET

df = pd.read_csv('/content/iris.csv')

In [68]:
# THIS CODE WILL RENAMES EACH OF THE COLUMNS WITH A MORE DESCRIPTIVE NAME FOR THE DATA THEY CONTAIN

df.rename(columns={
    "Type": "Plant Class",
    "PW": "Petal Width",
    "PL": "Petal Length",
    "SW": "Sepal Width",
    "SL": "Sepal Length"
})

     Plant Class  Petal Width  Petal Length  Sepal Width  Sepal Length
0              0            2            14           33            50
1              1           24            56           31            67
2              1           23            51           31            69
3              0            2            10           36            46
4              1           20            52           30            65
..           ...          ...           ...          ...           ...
145            1           20            50           25            57
146            2           13            40           23            55
147            0            2            17           34            54
148            1           24            51           28            58
149            0            2            15           37            53

[150 rows x 5 columns]

In [69]:
# PROVIDES THE FIRST 6 VALUES AND INFORMATION OF THE DATASET

(df.head(6))

   Type  PW  PL  SW  SL
0     0   2  14  33  50
1     1  24  56  31  67
2     1  23  51  31  69
3     0   2  10  36  46
4     1  20  52  30  65
5     1  19  51  27  58

In [70]:
# PROVIDES THE LAST 3 VALUES AND THEIR INFORMATION OF THE DATASET

(df.tail(3))

     Type  PW  PL  SW  SL
147     0   2  17  34  54
148     1  24  51  28  58
149     0   2  15  37  53

In [71]:
# PROVIDES THE STATESTICAL INFROMATION OF THE DATASET

df.describe()

             Type          PW          PL          SW          SL
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     1.000000   11.926667   37.786667   30.553333   58.446667
std      0.819232    7.569008   17.776233    4.372791    8.268592
min      0.000000    1.000000   10.000000   20.000000   43.000000
25%      0.000000    3.000000   16.000000   28.000000   51.000000
50%      1.000000   13.000000   44.000000   30.000000   58.000000
75%      2.000000   18.000000   51.000000   33.000000   64.000000
max      2.000000   25.000000   69.000000   44.000000   79.000000

In [72]:
# PROVIDES ALL THE ROWS IN THE IRIS DATASET THAT HAVE A PW GREATER THAN 10 AND A PL GREATER THAN 50
df[(df['PW'] > 10) & (df['PL'] > 50)]

     Type  PW  PL  SW  SL
1       1  24  56  31  67
2       1  23  51  31  69
4       1  20  52  30  65
5       1  19  51  27  58
19      1  21  56  28  64
25      1  19  51  27  58
27      1  18  55  31  64
34      1  23  57  32  69
37      1  18  58  25  67
41      1  21  54  31  69
42      1  25  61  36  72
44      1  21  55  30  68
50      1  22  56  28  64
51      1  15  51  28  63
55      1  23  59  32  68
56      1  23  54  34  62
57      1  25  57  33  67
60      1  18  51  30  59
61      1  23  53  32  64
63      1  21  57  33  67
66      1  18  60  32  72
74      1  23  61  30  77
84      2  13  54  29  62
92      1  20  51  32  65
99      1  25  60  33  63
103     2  16  51  27  60
104     1  18  55  30  65
106     1  22  67  38  77
107     1  21  66  30  76
108     1  13  52  30  67
112     1  20  64  38  79
114     1  20  67  28  77
118     1  14  56  26  61
124     1  24  56  34  63
125     1  16  58  30  72
126     1  21  59  30  71
127     1  18  56  29  63
129     1  23  69  26  77
130     2  13  56  29  66
134     1  19  61  28  74
136     1  18  63  29  73
140     1  22  58  30  65
143     1  19  53  27  64
148     1  24  51  28  58

In [78]:
# CREATES THE COPY OF THE 'TYPES' COLUMN AND NAME THE NEW COLUMN IN THE DATA FRAME 'SPECIES'

df['Species'] = df['Type'].copy()

In [81]:
# CREATES A RECENTLY UPDATED DATA FRAME TO ANEW FILE IN OUT DATASETS FOLDER CALLED 'new_iris.csv'

df.to_csv("/content/new_iris.csv", index=False)

# ADVANCE EXERCISES

In [87]:
# 1. Get the lowest and highest value of the Petal width for each class.

pw_min_max = df.groupby("Type")["PW"].agg(["min", "max"])
print(pw_min_max)

      min  max
Type
0       1    6
1      13   25
2      10   18

In [88]:
# 2. Get the shape and description of the iris dataset

# Shape
print("Shape of dataset:", df.shape)

# Description
print("\nDescription of dataset:\n", df.describe())

Shape of dataset: (150, 6)

Description of dataset:
              Type          PW          PL          SW          SL
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     1.000000   11.926667   37.786667   30.553333   58.446667
std      0.819232    7.569008   17.776233    4.372791    8.268592
min      0.000000    1.000000   10.000000   20.000000   43.000000
25%      0.000000    3.000000   16.000000   28.000000   51.000000
50%      1.000000   13.000000   44.000000   30.000000   58.000000
75%      2.000000   18.000000   51.000000   33.000000   64.000000
max      2.000000   25.000000   69.000000   44.000000   79.000000

In [89]:
# 3. Count the number of each Species in the dataset.

species_count = df["Type"].value_counts()
print(species_count)

Type
0    50
1    50
2    50
Name: count, dtype: int64

In [90]:
# 4. Get a new dataset that will display records only with species "Iris-setosa".

# Assuming Type=0 corresponds to Iris-setosa
setosa_df = df[df["Type"] == 0]

# Display first 5 rows
print(setosa_df.head())

    Type  PW  PL  SW  SL      Species
0      0   2  14  33  50  Iris-setosa
3      0   2  10  36  46  Iris-setosa
10     0   2  16  31  48  Iris-setosa
12     0   1  14  36  49  Iris-setosa
13     0   2  13  32  44  Iris-setosa

In [92]:
# MAPS THE NUMERIC LABELS TO ACTUAL SPECIES NAMES

df["Species"] = df["Type"].map({0: "Iris-setosa", 1: "Iris-versicolor", 2: "Iris-virginica"})